export { default as userRouter } from './user/userRouter'
export { default as tripRouter } from './trips/tripRouter'
export { default as emailRouter } from './email/emailRouter'
export { default as popularTripsRouter } from './popularTrips/popularTripsRouter'
export { default as cartRouter } from './cart/cartRouter'
export { default as cartItemRouter } from './cartItem/cartItemRouter'
